import type { RecommendedItemDefinition } from '@/shared/types';
import { createRecommendedItemId } from '@/shared/types';
import { DAILY_WATER_PER_PERSON } from '@/shared/utils/constants';

export const RECOMMENDED_ITEMS: RecommendedItemDefinition[] = [
  // ===================================================================
  // 1. Water & Beverages
  // ===================================================================
  {
    id: createRecommendedItemId('bottled-water'),
    i18nKey: 'products.bottled-water',
    category: 'water-beverages',
    baseQuantity: DAILY_WATER_PER_PERSON,
    unit: 'liters',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 12,
  },
  {
    id: createRecommendedItemId('long-life-milk'),
    i18nKey: 'products.long-life-milk',
    category: 'water-beverages',
    baseQuantity: 2,
    unit: 'liters',
    scaleWithPeople: true,
    scaleWithDays: false,
    defaultExpirationMonths: 12,
  },
  {
    id: createRecommendedItemId('long-life-juice'),
    i18nKey: 'products.long-life-juice',
    category: 'water-beverages',
    baseQuantity: 2,
    unit: 'liters',
    scaleWithPeople: true,
    scaleWithDays: false,
    defaultExpirationMonths: 12,
  },

  // ===================================================================
  // 2. Food
  // Calorie values: ~2000 kcal/day/adult recommended for emergency situations
  // ===================================================================
  {
    id: createRecommendedItemId('canned-soup'),
    i18nKey: 'products.canned-soup',
    category: 'food',
    baseQuantity: 1,
    unit: 'cans',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 24,
    weightGramsPerUnit: 400,
    caloriesPer100g: 50,
    caloriesPerUnit: 200, // ~200 kcal per can (400g can)
  },
  {
    id: createRecommendedItemId('canned-vegetables'),
    i18nKey: 'products.canned-vegetables',
    category: 'food',
    baseQuantity: 1,
    unit: 'cans',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 24,
    weightGramsPerUnit: 400,
    caloriesPer100g: 25,
    caloriesPerUnit: 100, // ~100 kcal per can (400g can)
  },
  {
    id: createRecommendedItemId('canned-fish'),
    i18nKey: 'products.canned-fish',
    category: 'food',
    baseQuantity: 0.67,
    unit: 'cans',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 36,
    weightGramsPerUnit: 150,
    caloriesPer100g: 130,
    caloriesPerUnit: 200, // ~200 kcal per can (150g drained)
  },
  {
    id: createRecommendedItemId('canned-meat'),
    i18nKey: 'products.canned-meat',
    category: 'food',
    baseQuantity: 0.67,
    unit: 'cans',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 36,
    weightGramsPerUnit: 200,
    caloriesPer100g: 150,
    caloriesPerUnit: 300, // ~300 kcal per can (200g can)
  },
  {
    id: createRecommendedItemId('pasta'),
    i18nKey: 'products.pasta',
    category: 'food',
    baseQuantity: 0.17,
    unit: 'kilograms',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 24,
    weightGramsPerUnit: 1000,
    caloriesPer100g: 350,
    caloriesPerUnit: 3500, // ~350 kcal per 100g dry pasta
    requiresWaterLiters: 1.0, // ~1 liter per kg of pasta for cooking
  },
  {
    id: createRecommendedItemId('rice'),
    i18nKey: 'products.rice',
    category: 'food',
    baseQuantity: 0.17,
    unit: 'kilograms',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 24,
    weightGramsPerUnit: 1000,
    caloriesPer100g: 360,
    caloriesPerUnit: 3600, // ~360 kcal per 100g dry rice
    requiresWaterLiters: 1.5, // ~1.5 liters per kg of rice for cooking (rice absorbs more)
  },
  {
    id: createRecommendedItemId('oats'),
    i18nKey: 'products.oats',
    category: 'food',
    baseQuantity: 0.17,
    unit: 'kilograms',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 12,
    weightGramsPerUnit: 1000,
    caloriesPer100g: 380,
    caloriesPerUnit: 3800, // ~380 kcal per 100g oats
    requiresWaterLiters: 2.0, // ~2 liters per kg of oats for porridge
  },
  {
    id: createRecommendedItemId('crackers'),
    i18nKey: 'products.crackers',
    category: 'food',
    baseQuantity: 0.67,
    unit: 'packages',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 12,
    weightGramsPerUnit: 200,
    caloriesPer100g: 250,
    caloriesPerUnit: 500, // ~500 kcal per package (200g)
  },
  {
    id: createRecommendedItemId('energy-bars'),
    i18nKey: 'products.energy-bars',
    category: 'food',
    baseQuantity: 2,
    unit: 'pieces',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 12,
    weightGramsPerUnit: 50,
    caloriesPer100g: 500,
    caloriesPerUnit: 250, // ~250 kcal per bar
  },
  {
    id: createRecommendedItemId('spreads'),
    i18nKey: 'products.spreads',
    category: 'food',
    baseQuantity: 1,
    unit: 'jars',
    scaleWithPeople: true,
    scaleWithDays: false,
    defaultExpirationMonths: 18,
    weightGramsPerUnit: 400,
    caloriesPer100g: 400,
    caloriesPerUnit: 1600, // ~1600 kcal per jar (peanut butter, 400g)
  },
  {
    id: createRecommendedItemId('dried-fruits'),
    i18nKey: 'products.dried-fruits',
    category: 'food',
    baseQuantity: 0.1,
    unit: 'kilograms',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 12,
    weightGramsPerUnit: 1000,
    caloriesPer100g: 300,
    caloriesPerUnit: 3000, // ~300 kcal per 100g
  },
  {
    id: createRecommendedItemId('nuts'),
    i18nKey: 'products.nuts',
    category: 'food',
    baseQuantity: 0.1,
    unit: 'kilograms',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 12,
    weightGramsPerUnit: 1000,
    caloriesPer100g: 600,
    caloriesPerUnit: 6000, // ~600 kcal per 100g
  },
  {
    id: createRecommendedItemId('salt-sugar'),
    i18nKey: 'products.salt-sugar',
    category: 'food',
    baseQuantity: 0.2,
    unit: 'kilograms',
    scaleWithPeople: false,
    scaleWithDays: false,
    // No calories - salt has 0, sugar is condiment
  },
  {
    id: createRecommendedItemId('coffee-tea'),
    i18nKey: 'products.coffee-tea',
    category: 'food',
    baseQuantity: 0.2,
    unit: 'kilograms',
    scaleWithPeople: true,
    scaleWithDays: false,
    defaultExpirationMonths: 18,
    // No significant calories
    requiresWaterLiters: 10, // ~10 liters per kg for brewing (about 50 cups per kg)
  },
  {
    id: createRecommendedItemId('frozen-vegetables'),
    i18nKey: 'products.frozen-vegetables',
    category: 'food',
    baseQuantity: 0.34,
    unit: 'kilograms',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 12,
    requiresFreezer: true,
    weightGramsPerUnit: 1000,
    caloriesPer100g: 40,
    caloriesPerUnit: 400, // ~40 kcal per 100g
  },
  {
    id: createRecommendedItemId('frozen-meat'),
    i18nKey: 'products.frozen-meat',
    category: 'food',
    baseQuantity: 0.17,
    unit: 'kilograms',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 6,
    requiresFreezer: true,
    weightGramsPerUnit: 1000,
    caloriesPer100g: 250,
    caloriesPerUnit: 2500, // ~250 kcal per 100g (average meat)
  },
  {
    id: createRecommendedItemId('frozen-meals'),
    i18nKey: 'products.frozen-meals',
    category: 'food',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: true,
    scaleWithDays: true,
    defaultExpirationMonths: 12,
    requiresFreezer: true,
    weightGramsPerUnit: 400,
    caloriesPer100g: 115,
    caloriesPerUnit: 450, // ~450 kcal per meal
  },

  // ===================================================================
  // 3. Cooking & Heat
  // ===================================================================
  {
    id: createRecommendedItemId('camping-stove'),
    i18nKey: 'products.camping-stove',
    category: 'cooking-heat',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('stove-fuel'),
    i18nKey: 'products.stove-fuel',
    category: 'cooking-heat',
    baseQuantity: 1,
    unit: 'canisters',
    scaleWithPeople: false,
    scaleWithDays: true,
    defaultExpirationMonths: 60,
  },
  {
    id: createRecommendedItemId('matches'),
    i18nKey: 'products.matches',
    category: 'cooking-heat',
    baseQuantity: 2,
    unit: 'boxes',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 60,
  },
  {
    id: createRecommendedItemId('lighter'),
    i18nKey: 'products.lighter',
    category: 'cooking-heat',
    baseQuantity: 2,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('candles'),
    i18nKey: 'products.candles',
    category: 'cooking-heat',
    baseQuantity: 10,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('fire-starter'),
    i18nKey: 'products.fire-starter',
    category: 'cooking-heat',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },

  // ===================================================================
  // 4. Light & Power
  // ===================================================================
  {
    id: createRecommendedItemId('flashlight'),
    i18nKey: 'products.flashlight',
    category: 'light-power',
    baseQuantity: 2,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('headlamp'),
    i18nKey: 'products.headlamp',
    category: 'light-power',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: true,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('batteries-aa'),
    i18nKey: 'products.batteries-aa',
    category: 'light-power',
    baseQuantity: 20,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 60,
  },
  {
    id: createRecommendedItemId('batteries-aaa'),
    i18nKey: 'products.batteries-aaa',
    category: 'light-power',
    baseQuantity: 12,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 60,
  },
  {
    id: createRecommendedItemId('batteries-d'),
    i18nKey: 'products.batteries-d',
    category: 'light-power',
    baseQuantity: 8,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 60,
  },
  {
    id: createRecommendedItemId('power-bank'),
    i18nKey: 'products.power-bank',
    category: 'light-power',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('charging-cables'),
    i18nKey: 'products.charging-cables',
    category: 'light-power',
    baseQuantity: 2,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('solar-charger'),
    i18nKey: 'products.solar-charger',
    category: 'light-power',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('power-generator'),
    i18nKey: 'products.power-generator',
    category: 'light-power',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('generator-fuel'),
    i18nKey: 'products.generator-fuel',
    category: 'light-power',
    baseQuantity: 10,
    unit: 'liters',
    scaleWithPeople: false,
    scaleWithDays: true,
    defaultExpirationMonths: 12,
  },

  // ===================================================================
  // 5. Communication
  // ===================================================================
  {
    id: createRecommendedItemId('battery-radio'),
    i18nKey: 'products.battery-radio',
    category: 'communication-info',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('hand-crank-radio'),
    i18nKey: 'products.hand-crank-radio',
    category: 'communication-info',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },

  // ===================================================================
  // 6. Medical & First Aid
  // ===================================================================
  {
    id: createRecommendedItemId('first-aid-kit'),
    i18nKey: 'products.first-aid-kit',
    category: 'medical-health',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 36,
  },
  {
    id: createRecommendedItemId('prescription-meds'),
    i18nKey: 'products.prescription-meds',
    category: 'medical-health',
    baseQuantity: 1,
    unit: 'days',
    scaleWithPeople: true,
    scaleWithDays: true,
  },
  {
    id: createRecommendedItemId('pain-relievers'),
    i18nKey: 'products.pain-relievers',
    category: 'medical-health',
    baseQuantity: 1,
    unit: 'packages',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 36,
  },
  {
    id: createRecommendedItemId('fever-reducers'),
    i18nKey: 'products.fever-reducers',
    category: 'medical-health',
    baseQuantity: 1,
    unit: 'packages',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 36,
  },
  {
    id: createRecommendedItemId('bandages'),
    i18nKey: 'products.bandages',
    category: 'medical-health',
    baseQuantity: 20,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 60,
  },
  {
    id: createRecommendedItemId('disinfectant'),
    i18nKey: 'products.disinfectant',
    category: 'medical-health',
    baseQuantity: 1,
    unit: 'bottles',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 36,
  },
  {
    id: createRecommendedItemId('thermometer'),
    i18nKey: 'products.thermometer',
    category: 'medical-health',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('antihistamines'),
    i18nKey: 'products.antihistamines',
    category: 'medical-health',
    baseQuantity: 1,
    unit: 'packages',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 36,
  },
  {
    id: createRecommendedItemId('diarrhea-meds'),
    i18nKey: 'products.diarrhea-meds',
    category: 'medical-health',
    baseQuantity: 1,
    unit: 'packages',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 36,
  },

  // ===================================================================
  // 7. Hygiene & Sanitation
  // ===================================================================
  {
    id: createRecommendedItemId('toilet-paper'),
    i18nKey: 'products.toilet-paper',
    category: 'hygiene-sanitation',
    baseQuantity: 1,
    unit: 'rolls',
    scaleWithPeople: true,
    scaleWithDays: true,
  },
  {
    id: createRecommendedItemId('wet-wipes'),
    i18nKey: 'products.wet-wipes',
    category: 'hygiene-sanitation',
    baseQuantity: 1,
    unit: 'packages',
    scaleWithPeople: true,
    scaleWithDays: false,
    defaultExpirationMonths: 24,
  },
  {
    id: createRecommendedItemId('hand-sanitizer'),
    i18nKey: 'products.hand-sanitizer',
    category: 'hygiene-sanitation',
    baseQuantity: 1,
    unit: 'bottles',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 24,
  },
  {
    id: createRecommendedItemId('soap'),
    i18nKey: 'products.soap',
    category: 'hygiene-sanitation',
    baseQuantity: 2,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('toothbrush'),
    i18nKey: 'products.toothbrush',
    category: 'hygiene-sanitation',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: true,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('toothpaste'),
    i18nKey: 'products.toothpaste',
    category: 'hygiene-sanitation',
    baseQuantity: 1,
    unit: 'tubes',
    scaleWithPeople: false,
    scaleWithDays: false,
    defaultExpirationMonths: 24,
  },
  {
    id: createRecommendedItemId('feminine-hygiene'),
    i18nKey: 'products.feminine-hygiene',
    category: 'hygiene-sanitation',
    baseQuantity: 0.34,
    unit: 'packages',
    scaleWithPeople: true,
    scaleWithDays: true,
  },
  {
    id: createRecommendedItemId('diapers'),
    i18nKey: 'products.diapers',
    category: 'hygiene-sanitation',
    baseQuantity: 10,
    unit: 'pieces',
    scaleWithPeople: true,
    scaleWithDays: true,
  },
  {
    id: createRecommendedItemId('garbage-bags'),
    i18nKey: 'products.garbage-bags',
    category: 'hygiene-sanitation',
    baseQuantity: 20,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('paper-towels'),
    i18nKey: 'products.paper-towels',
    category: 'hygiene-sanitation',
    baseQuantity: 2,
    unit: 'rolls',
    scaleWithPeople: false,
    scaleWithDays: false,
  },

  // ===================================================================
  // 8. Tools & Supplies
  // ===================================================================
  {
    id: createRecommendedItemId('bucket'),
    i18nKey: 'products.bucket',
    category: 'tools-supplies',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('water-container'),
    i18nKey: 'products.water-container',
    category: 'tools-supplies',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('duct-tape'),
    i18nKey: 'products.duct-tape',
    category: 'tools-supplies',
    baseQuantity: 1,
    unit: 'rolls',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('multi-tool'),
    i18nKey: 'products.multi-tool',
    category: 'tools-supplies',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('can-opener'),
    i18nKey: 'products.can-opener',
    category: 'tools-supplies',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('plastic-bags'),
    i18nKey: 'products.plastic-bags',
    category: 'tools-supplies',
    baseQuantity: 20,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('aluminum-foil'),
    i18nKey: 'products.aluminum-foil',
    category: 'tools-supplies',
    baseQuantity: 1,
    unit: 'rolls',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('plastic-wrap'),
    i18nKey: 'products.plastic-wrap',
    category: 'tools-supplies',
    baseQuantity: 1,
    unit: 'rolls',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('rope'),
    i18nKey: 'products.rope',
    category: 'tools-supplies',
    baseQuantity: 10,
    unit: 'meters',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('work-gloves'),
    i18nKey: 'products.work-gloves',
    category: 'tools-supplies',
    baseQuantity: 2,
    unit: 'pairs',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('whistle'),
    i18nKey: 'products.whistle',
    category: 'tools-supplies',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: true,
    scaleWithDays: false,
  },

  // ===================================================================
  // 9. Cash & Documents
  // ===================================================================
  {
    id: createRecommendedItemId('cash'),
    i18nKey: 'products.cash',
    category: 'cash-documents',
    baseQuantity: 300,
    unit: 'euros',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('document-copies'),
    i18nKey: 'products.document-copies',
    category: 'cash-documents',
    baseQuantity: 1,
    unit: 'sets',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
  {
    id: createRecommendedItemId('contact-list'),
    i18nKey: 'products.contact-list',
    category: 'cash-documents',
    baseQuantity: 1,
    unit: 'pieces',
    scaleWithPeople: false,
    scaleWithDays: false,
  },
];

/**
 * Get a recommended item by its ID
 */
export function getRecommendedItemById(
  id: string,
): RecommendedItemDefinition | undefined {
  return RECOMMENDED_ITEMS.find((item) => item.id === id);
}

/**
 * Get all recommended items for a specific category
 */
export function getRecommendedItemsByCategory(
  categoryId: string,
): RecommendedItemDefinition[] {
  return RECOMMENDED_ITEMS.filter((item) => item.category === categoryId);
}
